add sast tests
sravni/.github pull request #115
Opened 2024-03-12 13:41 UTC by aleksey-zagorulko

2024-03-12 13:46 UTC, kirillkarelin1934 requested changes

2024-03-12 13:46 UTC, kirillkarelin1934 commented on .github/workflows/publish-to-dev-harbor.yaml
> +        run: >
Отступ неверный 
Должен быть мультилайн вместо >

2024-03-13 19:46 UTC, aleksey-zagorulko commented on .github/workflows/publish-to-dev-harbor.yaml
> +        - name: Run SAST scan tests
Поправил

2024-03-14 07:07 UTC, kirillkarelin1934 approved these changes

2024-03-14 07:32 UTC, merged