dev-381/workflow-templates/pipeline without docker in docker
sravni/.github pull request #9
Opened 2021-12-09 13:41 UTC by ne-olegg

2021-12-10 09:11 UTC, aleksandrovpa requested changes

2021-12-10 09:11 UTC, aleksandrovpa commented on workflow-templates/sravni-pipeline-publish-to-stage-backoffices.yml
> +        working-directory: ./charts/generic-application/
ты же вроде хотел не менять тут?

2021-12-10 09:11 UTC, aleksandrovpa commented on workflow-templates/sravni-pipeline-publish-to-stage-manifest.yml
> +            cat app/k8s/ya-stage.yaml | envsubst | kubectl apply -f -
тут точно не надо ./app/k8s/ya-stage.yaml указывать?

2021-12-10 09:11 UTC, aleksandrovpa commented on workflow-templates/sravni-pipeline-publish-to-stage-mono.yml
> +          ref: 'v0.5.0'
надо бы рефы выносить в глобальные секреты, чтобы мы могли массово менять, если потребуется. а не ходить по всем репозиторям

2021-12-10 09:11 UTC, aleksandrovpa commented on workflow-templates/sravni-pipeline-publish-to-stage-multi-services.yml
> +          ref: DEV-103
кривой реф

2021-12-10 09:11 UTC, aleksandrovpa commented on workflow-templates/sravni-pipeline-publish-to-stage-multi-services.yml
> +        working-directory: ./charts/generic-application/
так, надо определиться как делаем везде. сейчас у тебя по-разному везде

2021-12-10 09:11 UTC, aleksandrovpa commented on workflow-templates/sravni-pipeline-publish-to-stage-php.yml
> +          ref: DEV-103
реф

2021-12-13 11:14 UTC, aleksandrovpa requested changes

2021-12-13 11:14 UTC, aleksandrovpa commented on workflow-templates/sravni-pipeline-publish-to-stage-backoffices.yml
> +          ref: '${{ secrets.CHARTS_REF }}'
надо бы где-то фиксировать, какой реф используется... может комментом в репе .github будем писать? тут же нельзя просто переменные добавлять, значения которых можно увидеть, только секреты...

2021-12-13 11:14 UTC, aleksandrovpa commented on workflow-templates/sravni-pipeline-publish-to-stage-mono.yml
> +          kubectl -n ${{ env.namespace }} create secret generic identity-key --from-file identity.pfx
давай тут тоже сделаем путь ./identity.pfx чтобы соблюдать консистентность везде

2021-12-13 11:14 UTC, aleksandrovpa commented on workflow-templates/sravni-pipeline-publish-to-stage-mono.yml
> +          cat qaenv/k8s-manifests/new-namespace-yandex.yml | envsubst | kubectl apply -f -
ну и тут тоже ./ добавим (выше везде тоже так сделай)

2021-12-13 11:41 UTC, aleksandrovpa approved these changes
lgtm

2021-12-13 14:30 UTC, ggselenskih approved these changes

2021-12-14 07:56 UTC, merged